name: Auto approve
on: 
  pull_request_target:
    branches:
      - main
    types: [opened, reopened]


jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4.0.0
        with:
          review-message: "Auto approved automated PR"
